# Generated by Django 5.0.2 on 2024-02-27 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=255)),
                ('lastname', models.CharField(max_length=255)),
                ('level', models.CharField(choices=[('11', 'Grade 11'), ('12', 'Grade 12')], max_length=2)),
                ('strand', models.CharField(choices=[('STEM', 'Science, Technology, Engineering, and Mathematics'), ('ABM', 'Accountancy, Business, and Management'), ('HUMSS', 'Humanities and Social Sciences')], max_length=5)),
                ('mail_type', models.CharField(choices=[('Gmail', 'Gmail'), ('Outlook', 'Microsoft Outlook'), ('Yahoo', 'Yahoo!')], max_length=15)),
                ('contact', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent'), ('Missing', 'Missing'), ('Injured', 'Injured'), ('Unknown', 'Unknown')], max_length=1)),
            ],
        ),
    ]
