# Generated by Django 5.0.2 on 2024-03-03 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent'), ('Missing', 'Missing'), ('Injured', 'Injured'), ('Unknown', 'Unknown')], max_length=10),
        ),
    ]
