# Generated by Django 5.0.2 on 2024-03-03 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_student_age_alter_student_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='mail_address',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
