# Generated by Django 5.0.2 on 2024-03-03 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_student_mail_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='num_id',
            field=models.CharField(max_length=12, null=True),
        ),
    ]
