# Generated by Django 5.0.2 on 2024-03-03 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_student_num_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='fullname',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
