# Generated by Django 5.0.2 on 2024-03-10 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_map'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='map',
            name='image',
        ),
    ]
