# Generated by Django 5.0.2 on 2024-03-10 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_alter_map_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='map',
            name='image',
        ),
        migrations.AddField(
            model_name='map',
            name='image_path',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
