# Generated by Django 5.0.2 on 2024-03-10 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_hazard_report'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Hazard_Report',
            new_name='Report',
        ),
    ]
