# Generated by Django 5.0.2 on 2024-03-10 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_rename_hazard_report_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='map',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='website.map'),
        ),
    ]
