# Generated by Django 5.0.2 on 2024-03-10 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0016_report_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('Standby', 'Not Used'), ('Active', 'In Use'), ('Removed', 'Removed')], max_length=255, null=True),
        ),
    ]
