# Generated by Django 5.0.3 on 2024-04-01 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0017_report_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='address',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='type',
            field=models.CharField(choices=[('Accident', 'Accident'), ('Damaged Area', 'Damaged Area'), ('Design Flaw', 'Design Flaw'), ('Electrical Appliance', 'Electrical Appliance'), ('Flammable', 'Flammable'), ('Explosive', 'Explosive'), ('Liquid Substance', 'Slippery or Corrosive Substance'), ('Unknown', 'Unknown')], max_length=255, null=True),
        ),
    ]
