# Generated by Django 5.0.3 on 2024-04-01 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0018_student_address_alter_report_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='guardian_No',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
